import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import { getSortedPostsData } from "@/lib/post";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  allPostData,
}: {
  allPostData: { date: string; title: string; id: string }[];
}) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>hello world</div>
        <section>
          <p>[Hannah Jeong Introduction]</p>
          <p>(this is a website)</p>
        </section>
        <section>
          <h2>Blog</h2>
          <ul>
            {allPostData.map(({ id, date, title }) => (
              <li key={id}>
                <a href={`/posts/${id}`}>{title}</a>
                <br />
                {date}
              </li>
            ))}
          </ul>
        </section>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const allPostData = getSortedPostsData();
  return {
    props: {
      allPostData,
    },
  };
};
