import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>hello world</div>
        <section>
          <p>[Hannah Jeong Introduction]</p>
          <p>(this is a website)</p>
        </section>
        <section>
          <h2>Blog</h2>
          <ul>
            <li>test</li>
          </ul>
        </section>
      </main>
    </>
  );
}
